#!/usr/bin/env bash
# source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/initial-dev/pop_os/install-packages)

if type nala >/dev/null
then
    pkg_man="nala"
else
    pkg_man="apt-get"
fi

# Make sure the universe package repository is installed
# Universe - Community-maintained free and open-source software.
# https://help.ubuntu.com/community/Repositories/Ubuntu
sudo add-apt-repository -y universe

# Update package repos
sudo "$pkg_man" update

# Update packages
sudo "$pkg_man" upgrade -y

# Install deb-get
# https://github.com/wimpysworld/deb-get
curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get
sudo deb-get update

# Setup GitHub CLI prerequisites
sudo mkdir -p -m 755 /etc/apt/keyrings && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
&& sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null

# Install packages
sudo "$pkg_man" install -y \
apt-transport-https \
apt-transport-https \
audacity \
autoconf \
autogen \
bat \
bison \
btop \
build-essential \
checkinstall \
cmake \
code \
darktable \
dialog \
docker.io \
dotnet-sdk-6.0 \
dotnet-sdk-7.0 \
dotnet-sdk-8.0 \
evolution \
evolution-ews \
ffmpeg \
flex \
fonts-cascadia-code \
fonts-firacode \
gh \
gimp \
git \
git \
git-extras \
gnome-tweaks \
golang \
gpg \
handbrake \
handbrake-cli \
hugo \
imagemagick \
jq \
kdiff3 \
libaacs-dev \
libavcodec-dev \
libavcodec-extra \
libavcodec-extra \
libbluray2 \
libcurl4-openssl-dev \
libfontconfig \
libfuse2 \
libssl-dev \
libtool \
lm-sensors \
lsb-release \
make \
mercurial \
mesa-utils \
mkvtoolnix \
neovim \
nmap \
nmon \
obs-studio \
openjdk-11-jdk \
pandoc \
pipx \
pv \
pwgen \
pylint \
python-is-python3 \
python3-autopep8 \
python3-pip \
ranger \
renameutils \
tar \
tmux \
twine \
ubuntu-restricted-extras \
ubuntu-restricted-extras \
universal-ctags \
wget \
xclip \
yadm \
zlib1g-dev \
zsh \
zsh-doc

# Install Gnome extensions
pipx install gnome-extensions-cli --system-site-packages
"$HOME"/.local/bin/gext install caffeine@patapon.info
"$HOME"/.local/bin/gext install blur-my-shell@aunetx
"$HOME"/.local/bin/gext install clipboard-history@alexsaveau.dev
"$HOME"/.local/bin/gext install freon@UshakovVasilii_Github.yahoo.com
"$HOME"/.local/bin/gext install paperwm@paperwm.github.com

"$HOME"/.local/bin/gext enable caffeine@patapon.info
"$HOME"/.local/bin/gext enable blur-my-shell@aunetx
"$HOME"/.local/bin/gext enable clipboard-history@alexsaveau.dev
"$HOME"/.local/bin/gext enable freon@UshakovVasilii_Github.yahoo.com
"$HOME"/.local/bin/gext enable paperwm@paperwm.github.com

sudo deb-get install \
android-messages-desktop \
fastfetch \
fd \
mdview \
papirus-icon-theme \
quickemu \
youtube-music

# add current user to docker group
echo "Adding current user to docker group..."
sudo usermod -aG docker $USER
