#!/usr/bin/env bash

# Detects the operating system and then performs a full bootstrap of the
# system by running the appropriate script.
# Usage:
# source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/bootstrap)

source /etc/os-release
if [[ "$ID" == "ubuntu" ]]
then
    source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/ubuntu/bootstrap)
elif [[ "$ID" == "pop" ]]
then
    source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/pop_os/bootstrap)
elif [[ "$ID" == "fedora" ]]
then
    source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/fedora/bootstrap)
elif [[ -d $HOME/.config/omarchy ]]
then
    source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/omarchy/bootstrap)
elif [["$ID" == "arch" ]]
then
    source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/arch/bootstrap)
else
    echo "Unsupported Linux distribution."
fi