#!/usr/bin/env bash

# Make sure the universe package repository is installed
# Universe - Community-maintained free and open-source software.
# https://help.ubuntu.com/community/Repositories/Ubuntu
sudo add-apt-repository -y universe

# Install graphical desktop packages
sudo apt-get install -y \
libfontconfig \
mesa-utils \
audacity \
pipx \
darktable \
evolution \
evolution-ews \
fonts-firacode \
gimp \
gnome-tweaks \
kdiff3 \
obs-studio \
xclip \
libavcodec-extra \
ubuntu-restricted-extras \
fonts-cascadia-code \
handbrake \
gnome-browser-connector \

deb-get update
deb-get install
android-messages-desktop \
youtube-music \
quickemu \
papirus-icon-theme \
mdview

pipx install gnome-extensions-cli --system-site-packages


"$HOME"/.local/bin/gext install caffeine@patapon.info
"$HOME"/.local/bin/gext install blur-my-shell@aunetx
"$HOME"/.local/bin/gext install clipboard-history@alexsaveau.dev
"$HOME"/.local/bin/gext install freon@UshakovVasilii_Github.yahoo.com
"$HOME"/.local/bin/gext install paperwm@paperwm.github.com

"$HOME"/.local/bin/gext enable caffeine@patapon.info
"$HOME"/.local/bin/gext enable blur-my-shell@aunetx
"$HOME"/.local/bin/gext enable clipboard-history@alexsaveau.dev
"$HOME"/.local/bin/gext enable freon@UshakovVasilii_Github.yahoo.com
"$HOME"/.local/bin/gext enable paperwm@paperwm.github.com