#!/usr/bin/env bash

# Install BluRay and DVD libraries
sudo apt-get install -y libbluray-bdj libaacs0 libdvd-pkg
sudo dpkg-reconfigure libdvd-pkg
mkdir -p ~/.config/aacs/
curl -k -L -o ~/.config/aacs/KEYDB.cfg http://vlc-bluray.whoknowsmy.name/files/KEYDB.cfg
