#!/usr/bin/env bash

# Perform a full bootstrap of Omarchy Linux, running all of the other scripts
# in this directory.
# Usage:
# source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/omarchy/bootstrap)

# Check if we're running on Omarchy Linux
if [[ ! -d $HOME/.config/omarchy ]]
then
    echo "Not running on Omarchy Linux, exiting."
    exit 1
fi

# Create an ssh key
source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/generic/create-ssh-key)

# Essential
source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/omarchy/install-essential-packages)

# JetBrains Toolbox
source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/generic/install-jetbrains-tools)

