#!/usr/bin/env bash

if type nala >/dev/null
then
    pkg_man="nala"
else
    pkg_man="apt-get"
fi

# Install commandline multimedia tools
sudo "$pkg_man" install -y \
ffmpeg \
handbrake-cli \
imagemagick \
mkvtoolnix
