#!/usr/bin/env bash
# source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/initial-dev/ubuntu/install-essential-packages)

if type nala >/dev/null
then
    pkg_man="nala"
else
    pkg_man="apt-get"
fi

# Update package repos
sudo "$pkg_man" update

# Update packages
sudo "$pkg_man" upgrade -y

# Install essential packages
sudo "$pkg_man" install -y \
gpg \
apt-transport-https \
lsb-release \
wget \
apt-transport-https \
bat \
btop \
docker.io \
git \
libfuse2 \
lm-sensors \
neovim \
nmap \
pv \
pwgen \
ranger \
renameutils \
tar \
tmux \
ubuntu-restricted-extras \
yadm \
zsh \
zsh-doc

# Install deb-get
# https://github.com/wimpysworld/deb-get
curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get
sudo deb-get update
sudo deb-get install \
fastfetch \
fd

# add current user to docker group
echo "Adding current user to docker group..."
sudo usermod -aG docker $USER
