#!/usr/bin/env bash
# source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/ubuntu/install-desktop-packages)

# Make sure the universe package repository is installed
# Universe - Community-maintained free and open-source software.
# https://help.ubuntu.com/community/Repositories/Ubuntu
sudo add-apt-repository -y universe

# Install Microsoft repo for VS Code
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/

sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
sudo apt install apt-transport-https
sudo apt update

if type nala >/dev/null
then
    pkg_man="nala"
else
    pkg_man="apt-get"
fi

# Update package repos
sudo "$pkg_man" install -y apt-transport-https
sudo "$pkg_man" update

# Install graphical desktop packages
sudo "$pkg_man" install -y \
audacity \
code \
darktable \
evolution \
evolution-ews \
fonts-cascadia-code \
fonts-firacode \
gimp \
gnome-browser-connector \
gnome-tweaks \
handbrake \
kdiff3 \
libavcodec-extra \
libfontconfig \
mesa-utils \
obs-studio \
pipx \
ubuntu-restricted-extras \
xclip \

deb-get update
deb-get install \
android-messages-desktop \
mdview
papirus-icon-theme \
quickemu \
youtube-music \

pipx install gnome-extensions-cli --system-site-packages


"$HOME"/.local/bin/gext install caffeine@patapon.info
"$HOME"/.local/bin/gext install blur-my-shell@aunetx
"$HOME"/.local/bin/gext install clipboard-history@alexsaveau.dev
"$HOME"/.local/bin/gext install freon@UshakovVasilii_Github.yahoo.com
"$HOME"/.local/bin/gext install paperwm@paperwm.github.com

"$HOME"/.local/bin/gext enable caffeine@patapon.info
"$HOME"/.local/bin/gext enable blur-my-shell@aunetx
"$HOME"/.local/bin/gext enable clipboard-history@alexsaveau.dev
"$HOME"/.local/bin/gext enable freon@UshakovVasilii_Github.yahoo.com
"$HOME"/.local/bin/gext enable paperwm@paperwm.github.com
