#!/usr/bin/env bash
# source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/initial-dev/ubuntu/install-dev-packages)

if type nala >/dev/null
then
    pkg_man="nala"
else
    pkg_man="apt-get"
fi

# Setup GitHub CLI prerequisites
sudo mkdir -p -m 755 /etc/apt/keyrings && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
&& sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null


# Install dev packages
sudo "$pkg_man" install -y \
autoconf \
autogen \
bison \
build-essential \
checkinstall \
cmake \
dialog \
dotnet-sdk-6.0 \
dotnet-sdk-7.0 \
dotnet-sdk-8.0 \
flex \
gh \
git \
git-extras \
golang \
hugo \
jq \
libaacs-dev \
libavcodec-dev \
libavcodec-extra \
libbluray2 \
libcurl4-openssl-dev \
libssl-dev \
libtool \
make \
mercurial \
openjdk-11-jdk \
pandoc \
pylint \
python-is-python3 \
python3-autopep8 \
python3-pip \
twine \
universal-ctags \
zlib1g-dev
