#!/usr/bin/env bash
# source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/ubuntu/install-desktop-packages)

# Make sure the universe package repository is installed
# Universe - Community-maintained free and open-source software.
# https://help.ubuntu.com/community/Repositories/Ubuntu
sudo add-apt-repository -y universe

# Install Microsoft repo for VS Code
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/

sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
sudo apt install apt-transport-https
sudo apt update

# Update package repos
sudo apt-get install -y apt-transport-https
sudo apt-get update

# Install graphical desktop packages
sudo apt-get install -y \
audacity \
code \
darktable \
evolution \
evolution-ews \
fonts-cascadia-code \
fonts-firacode \
gimp \
gnome-browser-connector \
gnome-tweaks \
handbrake \
kdiff3 \
libavcodec-extra \
libfontconfig \
mesa-utils \
obs-studio \
pipx \
ubuntu-restricted-extras \
xclip \

deb-get update
deb-get install \
android-messages-desktop \
mdview
papirus-icon-theme \
quickemu \
youtube-music \

pipx install gnome-extensions-cli --system-site-packages


"$HOME"/.local/bin/gext install caffeine@patapon.info
"$HOME"/.local/bin/gext install clipboard-history@alexsaveau.dev
"$HOME"/.local/bin/gext install freon@UshakovVasilii_Github.yahoo.com

"$HOME"/.local/bin/gext enable caffeine@patapon.info
"$HOME"/.local/bin/gext enable clipboard-history@alexsaveau.dev
"$HOME"/.local/bin/gext enable freon@UshakovVasilii_Github.yahoo.com

# Move window buttons to the left
gsettings get org.gnome.desktop.wm.preferences button-layout
gsettings set org.gnome.desktop.wm.preferences button-layout close,minimize,maximize:

# Install Chrome Remote Desktop
curl -O https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
sudo apt install  ./chrome-remote-desktop_current_amd64.deb
rm chrome-remote-desktop_current_amd64.deb

# Install GhosTTY
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/mkasberg/ghostty-ubuntu/HEAD/install.sh)"

# Install auto-cpufreq
source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/generic/auto-cpufreq)
