#!/usr/bin/env bash
# source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/ubuntu/install-essential-packages)

# Update package repos
sudo apt-get update

# Update packages
sudo apt-get upgrade -y

# Install essential packages
sudo apt-get install -y \
gpg \
apt-transport-https \
lsb-release \
wget \
apt-transport-https \
bat \
btop \
detox \
docker.io \
git \
libfuse2 \
lm-sensors \
neovim \
nmap \
pipx \
pv \
pwgen \
ranger \
rclone \
renameutils \
tar \
tmux \
ubuntu-restricted-extras \
yadm \
zsh \
zsh-doc

pipx install mnamer

# Install deb-get
# https://github.com/wimpysworld/deb-get

curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get
sudo deb-get update
sudo deb-get install \
fastfetch \
fd \
mdview
