#!/usr/bin/env bash
# source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/ubuntu/install-media-cli-tools)

# Install commandline multimedia tools
sudo apt-get install -y \
ffmpeg \
handbrake-cli \
imagemagick \
mkvtoolnix
