#!/usr/bin/env bash
# source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/ubuntu/install-makemkv)

# Install makemkv
if ! type makemkv
then
    MAKEMKV_VERSION="1.18.2"
    mkdir -p /tmp/makemkv-build
    pushd /tmp/makemkv-build || return 1

    curl -O "https://www.makemkv.com/download/makemkv-bin-$MAKEMKV_VERSION.tar.gz"
    curl -O "https://www.makemkv.com/download/makemkv-oss-$MAKEMKV_VERSION.tar.gz"
    curl -O https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2

    tar xzvf "makemkv-bin-$MAKEMKV_VERSION.tar.gz"
    tar xzvf "makemkv-oss-$MAKEMKV_VERSION.tar.gz"
    tar xjvf ffmpeg-snapshot.tar.bz2

    popd || return 1

    sudo apt-get install -y \
    build-essential \
    pkg-config \
    libc6-dev \
    libssl-dev \
    libexpat1-dev \
    libavcodec-dev \
    libgl1-mesa-dev \
    qtbase5-dev \
    zlib1g-dev \
    yasm \
    libfdk-aac-dev \
    nasm

    pushd /tmp/makemkv-build/ffmpeg || return 1
    ./configure --prefix=/tmp/ffmpeg --enable-static --disable-shared --enable-pic --enable-libfdk-aac
    make install
    popd || return 1

    pushd "/tmp/makemkv-build/makemkv-oss-$MAKEMKV_VERSION" || return 1
    PKG_CONFIG_PATH=/tmp/ffmpeg/lib/pkgconfig ./configure
    make
    sudo make install
    popd || return 1

    pushd "/tmp/makemkv-build/makemkv-bin-$MAKEMKV_VERSION" || return 1
    make
    sudo make install
    popd || return 1
fi
