#!/usr/bin/env bash
# source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/arch/install-essential-packages)

# Enable multilib repository
echo "Enabling multilib repository..."
PACMAN_CONF="/etc/pacman.conf"
# Check if the multilib section is already uncommented
if grep -q "^\\[multilib\\]" "$PACMAN_CONF"; then
    echo "Multilib repository is already enabled in $PACMAN_CONF."
else
    echo "Enabling multilib repository in $PACMAN_CONF..."
    echo "Backing up /etc/pacman.conf..."
    sudo cp $PACMAN_CONF "$PACMAN_CONF.bak"
    # Uncomment the [multilib] section and its Include line
    sudo sed -i '/^#\[multilib\]/{s/^#//; n; s/^#//}' "$PACMAN_CONF"
    echo "Multilib repository enabled."
fi

# Update packages repos
echo "Updating package repositories..."
sudo pacman -Syy

# Install essential packages
sudo pacman -S --needed \
detox \
firefox \
git-extras \
gpg \
hugo \
jq \
lm_sensors \
nc \
nmap \
pv \
pwgen \
python-pipx \
ranger \
rclone \
renameutils \
steam \
starship \
udisks2 \
vlc \
yadm \
zsh \
zsh-completions \
zsh-doc 
 
# Install mdview from AUR
# yay doesn't seem to detect the dependencies for some reason
git clone https://aur.archlinux.org/mdview.git
cd mdview
makepkg -si
cd ..
rm -rf mdview

# Install mnamer to help rename media files
# https://github.com/jkwill87/mnamer
pipx install mnamer


# Install packages from AUR
yay -S \
localsend \
visual-studio-code-bin \

# Change default shell to zsh
if [[ "$SHELL" != "/usr/bin/zsh" ]]
then
    echo "Changing default shell to zsh..."
    chsh -s /usr/bin/zsh
fi  
