#!/usr/bin/env bash
source /etc/os-release
sudo dnf -y install dnf-plugins-core

# install Microsoft repo for VS Code
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

sudo dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# Add YADM repo
# https://yadm.io/
sudo dnf config-manager addrepo --from-repofile=https://download.opensuse.org/repositories/home:TheLocehiliosan:yadm/Fedora_$VERSION_ID/home:TheLocehiliosan:yadm.repo

# Add docker repo
sudo dnf config-manager addrepo --from-repofile=https://download.docker.com/linux/fedora/docker-ce.repo

# Add Starhip prompt repo
# https://starship.rs/
sudo dnf copr enable atim/starship

sudo dnf update
sudo dnf -y upgrade

sudo dnf install -y \
    NetworkManager-tui \
    audacity \
    autoconf \
    autogen \
    bat \
    bison \
    cascadia-code-fonts\ \
    code \
    coreutils \
    ctags \
    darktable \
    detox \
    dialog \
    dnf-plugin-system-upgrade \
    docker \
    dotnet-sdk-9.0 \
    edk2-tools \
    evolution \
    fastfetch \
    ffmpeg \
    ffmpeg-devel \
    fira-code-fonts \
    flex \
    fontawesome-fonts \
    gcc \
    genisoimage \
    gh \
    gimp \
    git-gui \
    gitk \
    gnome-shell-extension-blur-my-shell \
    gnome-shell-extension-caffeine \
    gnome-shell-extension-dash-to-dock \
    gnome-shell-extension-freon \
    gnome-tweaks \
    golang \
    gpaste \
    gpaste-bash-completion \
    gpaste-ui \
    gpaste-zsh-completion \
    htop \
    install \
    java-latest-openjdk \
    jq \
    kdiff3 \
    krita \
    libtool \
    light \
    make \
    mercurial \
    neovim \
    net-snmp \
    net-snmp-devel \
    net-snmp-libs \
    net-snmp-utils \
    pandoc \
    pipx \
    powerline-fonts \
    procps \
    pwgen \
    pylint \
    python3 \
    python3-autopep8 \
    python3-netifaces \
    python3-pip \
    python3-psutil \
    python3-pypandoc \
    python3-requests \
    qemu \
    ranger \
    rclone \
    rpmdevtools \
    rpmlint \
    spice-gtk-tools \
    starship \
    tito \
    tmux \
    twine \
    unzip \
    usbutils \
    util-linux \
    util-linux-user \
    w3m \
    w3m-img \
    wget \
    xdg-user-dirs \
    yadm \
    zoxide \
    zsh \
    --allowerasing

# Set up Neovim as an alternative to vim
sudo update-alternatives --install /usr/bin/vim vim $(which nvim) 10

# Install CLI for installing Gnome Extensions
pipx install gnome-extensions-cli --system-site-packages

# Install Gnome Extensions
"$HOME"/.local/bin/gext install paperwm@paperwm.github.com

# Install mnamer
pipx install mnamer

# Enable docker and start it
sudo systemctl enable docker && sudo systemctl start docker
