#!/usr/bin/env bash
# source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/generic/create-ssh-key)

if [[ -f "$HOME/.ssh/id_ed25519" ]]; then
    echo "SSH key ~/.ssh/id_ed25519 already exists, skipping."
else
    ssh-keygen -t ed25519 -f "$HOME/.ssh/id_ed25519"
fi
