#!/usr/bin/env bash
# source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/generic/github-auth-login)

echo "Auth/Login for GitHub CLI."
if gh auth status --hostname github.com >/dev/null 2>&1; then
    echo "Already authenticated with GitHub CLI, skipping."
else
    gh auth login --web --scopes "admin:public_key"
fi
