#!/usr/bin/env bash
# source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/generic/github-add-key)

if type $HOME/.ssh/id_ed25519.pub > /dev/null 2>&1
then
    gh ssh-key add $HOME/.ssh/id_ed25519.pub
else if type $HOME/.ssh/id_rsa.pub > /dev/null 2>&1
    then
    gh ssh-key add $HOME/.ssh/id_rsa.pub;
fi
