#!/usr/bin/env bash
# source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/generic/install-tmux-catppuccin-theme)

mkdir -p ~/.config/tmux/plugins/catppuccin
git clone -b v2.1.3 https://github.com/catppuccin/tmux.git ~/.config/tmux/plugins/catppuccin/tmux

echo "Catppuccin theme for tmux has been installed."
echo "To apply the theme, add the following line to your .tmux.conf file:"
echo "run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux"
