#!/usr/bin/env bash
# source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/generic/install-jetbrains-tools)

# Install JetBrains Toolbox
# https://www.jetbrains.com/lp/toolbox/
base_filename=jetbrains-toolbox-3.2.0.65851

curl -L -o /tmp/$base_filename.tar.gz https://download.jetbrains.com/toolbox/$base_filename.tar.gz
tar xzvf /tmp/$base_filename.tar.gz -C /tmp
"/tmp/$base_filename/bin/jetbrains-toolbox" >/dev/null 2>&1 &
# rm "/tmp/$base_filename.tar.gz"
# rm -rf "/tmp/jetbrains-toolbox-$base_filename"
echo "JetBrains Toolbox installation initiated. Please complete the setup through the application interface."
