#!/usr/bin/env bash
# source <(curl -fsSL https://raw.githubusercontent.com/mapitman/linux-bootstrap/main/generic/install-jetbrains-tools)

# Install JetBrains Toolbox
# https://www.jetbrains.com/lp/toolbox/
# NOTE: Update this version periodically when a new JetBrains Toolbox release is desired.
JETBRAINS_TOOLBOX_VERSION=3.2.0.65851
base_filename="jetbrains-toolbox-$JETBRAINS_TOOLBOX_VERSION"

if [[ -f "$HOME/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox" ]] || command -v jetbrains-toolbox >/dev/null 2>&1; then
    echo "JetBrains Toolbox is already installed, skipping."
else
    curl -L -o /tmp/$base_filename.tar.gz https://download.jetbrains.com/toolbox/$base_filename.tar.gz
    tar xzvf /tmp/$base_filename.tar.gz -C /tmp

    if [ -f "/tmp/$base_filename/bin/jetbrains-toolbox" ]; then
        echo "JetBrains Toolbox downloaded and extracted successfully."
    else
        echo "Failed to download or extract JetBrains Toolbox."
        return 1
    fi
    "/tmp/$base_filename/bin/jetbrains-toolbox" >/dev/null 2>&1 &
    echo "JetBrains Toolbox installation initiated. Please complete the setup through the application interface."
fi
